_includes/breadcrumb-theme-wet-boew-en.html
_includes/breadcrumb-theme-wet-boew-fr.html
_includes/content-buttons-en.html
_includes/footer-theme-wet-boew-en.html
_includes/footer-theme-wet-boew-fr.html
_includes/header-theme-wet-boew-en.html
_includes/header-theme-wet-boew-fr.html
_includes/sitemenu-theme-wet-boew-en.html
_includes/sitemenu-theme-wet-boew-fr.html
_layouts/default-theme-wet-boew-en.html
decision/1.md
decision/2.md
decision/index-en.md
decision/index-en.textitle
decision/template.md
governance/index-en.md
index-en.md
index-fr.md
index.html
mitigation-en.md
projects-en.md
research-en.md
research/1-datalist-JSON-suggestion.md
roadmap-en.md
test-case/2018-1.md

Initial commit of reboot of wet-boew documentation website

Reboot of wet-boew documentation

---

research/2018-6-wb5-exploration-1.md

Documentation for countdown

---

research/2018-assets/2018-11-prototype/stacks/docs/nav-demo.html
research/2018-assets/2018-11-prototype/stacks/src/module/nav.js
research/2018-assets/2018-11-prototype/stacks/theme/style.css

Demo for keyboard navigation module.

Key Nav Demo

---

research/2019-15-exploration-chat-pattern-prototype-form.md
research/2019-15-exploration-chat-pattern.md

Still needs some testing for mobile UX.

Research 2019-15 Working Copy

---

_data/jquery3migration/breakingchanges.json
_data/jquery3migration/plugins.json
_data/jquery3migration/polyfills.json
research/2019-16-jquery-3-migration.md

These commits encompass the new documentation / research page for the jQuery 3 Migration Project. 
A preview can be seen here: https://neilmispelaar.github.io/wet-boew-documentation/research/2019-16-jquery-3-migration.html

Documentation for jQuery 3 Migration Project

---

decision/8.md
decision/index-en.md

Initial draft + proposition of a design decision on how to implement JSON-LD with RDFa in a single web page

Design decision on how to implement JSON-LD with RDFa in a web page

---

research/2019-17-datepicker.md

I sent an original email to Pierre Dubois and I added it here in github.

Added my informations from the original email.

---

decision/9.md
decision/index-en.md

To be presented on October 23, 2019.

Design decision 9: Release early, release often

---

index-en.md
research/2020-22-a11y-content-inst-service-performance.md
research/2020-23-a11y-tables.md
research/2020-24-a11y-tabs-carousel.md
research/2020-25-a11y-event.md
research/2020-26-a11y-feddback.md
research/2020-27-a11y-audience.md
research/2020-28-a11y-institution-contact.md
research/2020-29-a11y-ministerial.md
research/2020-30-a11y-theme.md
research/2020-31-a11y-topic-page.md

Implementing changes requested from #232

Broken link and format fixed for GC Web Reports

---

decision/11.md

design decision regarding wcag 1.4.4 - resize text is added.

design decision regarding wcag 1.4.4

---

decision/11.md
decision/index-en.md

DD 11 - Did an initial review

---

index-en.md
research/research-2020-32-a11y.md

WCAG2.1 Assessment report on WET-BOEW Homepage

accessibility documents added

---

research/2019-19-add-calendar.md

Minor edits to research document

2019-19 add to calendar - update reseach document

---

index-en.md
research/research-2020-33-a11y.md
research/research-2020-34-a11y.md

Conducted WCAG assessment on first two pages of child benefit pages.

WCAG Assessment on Child Benefit Pages

---

decision/13.md
decision/index-en.md

Related to wet-boew/wet-boew#8815.

Add design decision 13: Reduce aggressiveness of form validation plugin

---

decision/13.md

Add WCAG 2.x references to design decision 13

---

.gitignore
research-en.md
research/2020-39--browser-usage.md

Publisher browser usage stats on wet-boew documentation

WET-139 Publisher browser usage stats on wet-boew documentation

---

governance/meeting.md
projects-en.md
research/1-datalist-JSON-suggestion.md

@GormFrank feel free to complement my meeting notes with yours.

Meeting note - WET Roadmap 2020-12-02

---

research/2020-39--browser-usage.md

2020-39: Fix browser numbers and add more recent ones

---

decision/14.md

Typos and tournures de phrases.

DD-14: Brief Revision

---

governance/meeting.md

@GormFrank can you specify the number of participant and I am missing some notes of our June 2022 WET Monthly meeting.

WET Monthly meeting 2022-09 notes/summary

---

decision/15.md

Desing Decision 15 - Content update

---

governance/meeting.md

Added the last monthly meeting notes : updated

Added the last meeting notes 

---

governance/meeting.md

Added notes of the last monthly meeting

Update meeting.md: Added notes of the last meeting
